### ISSUE TITLE
Using bookmarklet on non-article page adds entry to database.

### ISSUE THREAD

**Issue by HarryRybacki-zz** [cos-labs/scinet-citelet#1]
### Steps:
1. Go to non-article page e.g.: www.plosbiology.org
2. Click Citelet bookmarklet
### Expected:
1. Bookmarklet stops operating after not identifying a publisher
### Actual:
1. Bookmarklet submits result and entry is added to DB.

**Comment by jmcarp** [comment]
Fixed in master. Thanks for catching this!

**Comment by HarryRybacki-zz** [comment]
Dude, you are awesome!
