### ISSUE TITLE
Option to turn off confirmation dialog results in a blank page

### ISSUE THREAD

**Issue by bnosek** [cos-labs/scinet-citelet#9]
image:

![screen shot 2014-02-12 at 5 05 19 pm](https://f.cloud.github.com/assets/1761504/2154763/5baba81a-943a-11e3-9207-41c5c84dcbd8.png)

**Comment by bnosek** [comment]
Just pinging this one.  It is still non-functional with my chrome browser (modern) and is a pretty essential fix for smooth experience.

**Comment by jmcarp** [comment]
I believe that development of the Chrome and other extensions has been shifted to https://github.com/asmacdo/kango-citelet. Once this is released, confirmation should be turned off by default. @hrybacki, @asmacdo: when do you think the new batch of extensions will be ready for release?

**Comment by asmacdo** [comment]
@HarryRybacki and I will try to get the new batch out this weekend.

**Comment by HarryRybacki-zz** [comment]
Indeed, we will get the updated extensions pushed and test them this weekend. Sorry for the delay. Cryptography has been taking up a very disproportionate amount of my time over the past few weeks :(

**Comment by HarryRybacki-zz** [comment]
Fixed in [commit ae5f2ca](https://github.com/CenterForOpenScience/scinet-citelet/commit/ae5f2cadd9e386827f27baccd4fe236af01ef3c1)
